{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    release: {{ .Values.monitoring.prometheusReleaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.metricsPath }}
      interval: 15s
{{- end }}
