app:
  name: inventory-service

replicaCount: 2

image:
  repository: sergiocosu/inventory-service
  tag: latest

container:
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi

service:
  type: ClusterIP
  port: 8080

health:
  livenessPath: /health/live
  readinessPath: /health/ready

monitoring:
  enabled: false
  metricsPath: /metrics
  prometheusReleaseLabel: monitoring