app:
  name: inventory-service

replicaCount: 1

image:
  repository: sergiocosu/inventory-service
  tag: latest

container:
  port: 8080

service:
  type: ClusterIP
  port: 8080

health:
  livenessPath: /health/live
  readinessPath: /health/ready