name: CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  build-test-analyze:
    name: Build, Test & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Java 17 (requerido por SonarScanner)
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache SonarCloud packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore Microservicios_y_Docker/InventoryService.sln

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"sergioandresco_Final-Project-Software-Architecture" \
            /o:"sergioandresco" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml" \
            /d:sonar.qualitygate.wait=true \
            
      - name: Build
        run: dotnet build Microservicios_y_Docker/InventoryService.sln --no-restore --configuration Release

      - name: Test with coverage
        run: >
          dotnet test Microservicios_y_Docker/InventoryService.sln
          --no-build --configuration Release
          --collect:"XPlat Code Coverage"
          --verbosity normal

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
